DOKUMENT = Analysis-I

make:
	pdflatex $(DOKUMENT).tex -output-format=pdf
	pdflatex $(DOKUMENT).tex -output-format=pdf
	make clean

clean:
	rm -rf  $(TARGET) *.class *.html *.log *.aux *.out *.thm *.idx *.toc
